---
build-image:
  stage: build
  script:
    - echo "Building project..."
    - echo $API_CONFIG > .env
        - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    #- npm install
    #- npm test

curl-test-job:
  stage: test
  script:
    - echo "Running CURL tests..."
    - echo $K8S_CONFIG > ./k8sconfig
    - npm install
    - kubectl get services --kubeconfig ./k8sconfig
    #- docker build -t annaarroyo/cs4783-spring2021-api-curl:latest -f Dockerfile_api .
    #- docker push annaarroyo/cs4783-spring2021-api-curl:latest
    #- kubectl apply -f k8s/deploy_api --kubeconfig ./k8sconfig
    #- sleep 5
    #- kubectl create secret docker-registry kvk745-dockerhub --docker-server=docker.io --docker-username=annaarroyo --docker-password=$ANNA_DOCKERHUB_TOKEN --docker-email=annaearroyo@gmail.com --kubeconfig ./k8sconfig
    #- kubectl apply -f k8s/service_api_lb_curl --kubeconfig ./k8sconfig
    #- sleep 10
    #- chmod +x ./curltesting/testcurl.sh
    #- ./curltesting/testcurl.sh

deploy-job:
  stage: deploy
  script:
    - echo "Deploying..."
    #- echo "$private_key_anna" > ./private_key
    #-chmod 400 ./private_key
    #- ssh -i ./private_key iaf873@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- ssh -i ./private_key kvk745@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- rm ./private_key
    
...
