---
build-image:
  stage: build
  script:
    - echo "Building project..."
    - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm install
    - npm test

curl-test-job:
  stage: test
  script:
    - echo "Running CURL tests..."
    - npm install
    - docker-compose up
    - sleep 10
    - chmod +x ./curltesting/testcurl.sh
    - ./curltesting/testcurl.sh

deploy-job:
  stage: deploy
  script:
    - echo "Deploying..."
    #- echo "$private_key_anna" > ./private_key
    #-chmod 400 ./private_key
    #- ssh -i ./private_key iaf873@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- ssh -i ./private_key kvk745@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- rm ./private_key
    
...
