---
build-job:
  stage: build
  script:
    - echo "Building project..."
    - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm install
    - npm test

curl-test-job:
  stage: test
  script:
    - echo "Deploying for CURL testing..."
    - npm install
    - echo "$private_key_nikki" > ./private_key
    #- echo "$private_key_anna" > ./private_key
    - chmod 400 ./private_key
    - ssh -i ./private_key iaf873@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- ssh -i ./private_key kvk745@10.100.201.3 "cd ~/cs4783-project-spring2021; git pull; pm2 stop 0"
    - rm ./private_key
    - sleep 10
    - echo "Running CURL tests..."
    - chmod +x ./curltesting/testcurl.sh
    - ./curltesting/testcurl.sh

deploy-job:
  stage: deploy
  script:
    - echo "Deploying to class server..."
    - echo "At this point, will ssh and pull"
    
...
