---
build-image:
  stage: build
  script:
    - echo "Building project..."
    - cat $API_CONFIG > ./.env
    - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    #- npm install
    #- npm test

curl-test-job:
  stage: test
  script:
    - echo "Running CURL tests..."
    - cat $K8S_CONFIG > ./k8sconfig
    - npm install
    #- kubectl get services --kubeconfig ./k8sconfig
    - docker build -t annaarroyo/cs4783-spring2021-api-curl:latest -f Dockerfile_api .
    - docker login --username=annaarroyo --password=$ANNA_DOCKERHUB_TOKEN
    - docker push annaarroyo/cs4783-spring2021-api-curl:latest
    - kubectl apply --kubeconfig ./k8sconfig -f ./k8s/deploy_api_curl.yaml
    - sleep 10
    - kubectl apply --kubeconfig ./k8sconfig -f ./k8s/service_api_lb_curl.yaml
    - sleep 5
    - kubectl get service cs4783-spring2021-api-lb_curl -o=jsonpath='{.status.loadBalancer.ingress[0].ip}' --kubeconfig ./k8sconfig > ip.sh
    - chmod +x ./setCurlIP.sh
    - ./setCurlIP.sh
    - chmod +x ./curlIP.sh
    - ./curlIP.sh
    - chmod +x ./curltesting/testcurl.sh
    - ./curltesting/testcurl.sh

deploy-job:
  stage: deploy
  script:
    - echo "Deploying..."
    #- echo "$private_key_anna" > ./private_key
    #-chmod 400 ./private_key
    #- ssh -i ./private_key iaf873@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- ssh -i ./private_key kvk745@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- rm ./private_key
    
...
