---
build-image:
  stage: build
  script:
    - echo "Building project..."
    - cat $API_CONFIG > ./.env
    - npm install

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    #- npm install
    #- npm test

curl-test-job:
  stage: test
  script:
    - echo "Running CURL tests..."
    - docker build -t api_image .
    - docker ps
    - docker run -p 2000:12036 -d api_image  
    - chmod +x ./curltesting/testcurl.sh
    - ./curltesting/testcurl.sh

deploy-job:
  stage: deploy
  script:
    - echo "Deploying..."
    #- echo "$private_key_anna" > ./private_key
    #-chmod 400 ./private_key
    #- ssh -i ./private_key iaf873@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- ssh -i ./private_key kvk745@10.100.201.3 "cd ~/cs4783DevOps; git pull; pm2 reload all"
    #- rm ./private_key
    
...
