apiVersion: v1
kind: Service
metadata:
  name: cs4783-spring2021-db-lb
spec:
  selector:
    app: cs4783-spring2021-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer